package com.atek.gate.app.database.entity

data class Product(

    val id: Int?,
    val pass_inventory_id: String?,
    val support_type_id: String?,
    val pass_id: String?,
    val active: String?,
    val name: String,
    val company_id: String?,
    val description: String,
    val qr_type_id: String?,
    val same_station_over_time: String?,
    val same_station_over_time_penalty: String?,
    val same_station_over_time_max_penalty: String?,
    val other_station_over_time: String?,
    val other_station_over_time_penalty: String?,
    val other_station_over_time_max_penalty: String?,
    val over_travelling_penalty: String?,
    val entry_exit_control: String?,
    val start_validity_period: String?,
    val end_validity_period: String?,
    val balance_forward: String?,
    val reload_permit: String?,
    val validity: String?,
    val validity_unit: String?,
    val entry_validity: String,
    val entry_validity_unit: String,
    val grace_period: String?,
    val fare_table_id: String,
    val fare_table_peak: String?,
    val fare_table_non_peak: String?,
    val registration_fee: String?,
    val refund_permit: String?,
    val refund_fee: String?,
    val registration_fee_refund_permit: String?,
    val registration_refund_fee: String?,
    val bundle_trips: String?,
    val daily_trip_control: String?,
    val max_daily_trip: String?,
    val max_balance: String?,
    val min_entry_value: String?,
    val max_exit_value: String?,
    val min_load_balance: String?,
    val min_reload_balance: String?,
    val steps_reload: String?,
    val entry_mismatch_penalty: String?,
    val exit_mismatch_penalty: String?,
    val free_exit_token_penalty: String?,
    val return_validity: String?,
    val return_validity_unit: String?,

)
